### ISSUE TITLE
How to setup?

### ISSUE THREAD

**Issue by fourwhey** [ta264/Lidarr.Plugin.Deemix#5]
I'm not sure how to install a plugin for Lidarr. Can you provide instructions?

Thank you.

**Comment by ta264** [comment]
Currently this is not for public consumption

**Comment by ftruzzi** [comment]
If it can be helpful for anyone: I migrated from a "normal" lidarr setup by switching the docker base image from linuxserver's to `hotio/lidarr:pr-plugins`. Then I was able to add this plugin by adding the repo URL in the new Plugins section. I then configured the plugin to point to an existing Deemix install.

I liked this approach more rather than switching to a different pre-packaged lidarr image with bells and whistles and the risk of breaking my existing config.

Thank you for the work, @ta264!
